package com.ops.expertsystem.regras.prestador.prestador_02;

rule "41301323_500" 
	salience 500
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "41301323") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "27450") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "69632") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("41301323","Itens { 27450, 69632 } realizados a partir do procedimento {41301323}. Prob: 100,00", "alerta" ) );
end

rule "41301323_499" 
	salience 499
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "41301323") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "27450") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90297300") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("41301323","Itens { 27450, 90297300 } realizados a partir do procedimento {41301323}. Prob: 100,00", "alerta" ) );
end

