package com.ops.expertsystem.regras.prestador.prestador_02;

rule "10102019_500" 
	salience 500
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60034335") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70015368") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705330") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 60034335, 70015368, 70705330 } realizados a partir do procedimento {10102019}. Prob: 87,50", "alerta" ) );
end

rule "10102019_499" 
	salience 499
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60000554") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90019881") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 60000554, 90019881 } realizados a partir do procedimento {10102019}. Prob: 83,33", "alerta" ) );
end

