package com.ops.expertsystem.regras.prestador.prestador_02;

rule "40304361_500" 
	salience 500
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60034335") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70015368") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70222789") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705259") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705330") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 60034335, 70015368, 70222789, 70705259, 70705330 } realizados a partir do procedimento {40304361}. Prob: 88,00", "alerta" ) );
end

rule "40304361_499" 
	salience 499
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60023252") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705259") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90279107") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 60023252, 70705259, 70705348, 90279107 } realizados a partir do procedimento {40304361}. Prob: 81,25", "alerta" ) );
end

rule "40304361_498" 
	salience 498
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "15800") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705259") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90279107") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 15800, 70705259, 70705348, 90279107 } realizados a partir do procedimento {40304361}. Prob: 83,57", "alerta" ) );
end

rule "40304361_496" 
	salience 496
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70015368") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70223190") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705259") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705330") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 70015368, 70223190, 70705259, 70705330 } realizados a partir do procedimento {40304361}. Prob: 88,00", "alerta" ) );
end

rule "40304361_495" 
	salience 495
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70222789") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70223190") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705259") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705330") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 70222789, 70223190, 70705259, 70705330 } realizados a partir do procedimento {40304361}. Prob: 91,67", "alerta" ) );
end

rule "40304361_494" 
	salience 494
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60034335") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70015368") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70222789") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705259") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 60034335, 70015368, 70222789, 70705259 } realizados a partir do procedimento {40304361}. Prob: 88,46", "alerta" ) );
end

rule "40304361_492" 
	salience 492
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60023252") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705259") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 60023252, 70705259, 70705348 } realizados a partir do procedimento {40304361}. Prob: 81,82", "alerta" ) );
end

rule "40304361_491" 
	salience 491
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "15800") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705259") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90279107") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 15800, 70705259, 90279107 } realizados a partir do procedimento {40304361}. Prob: 83,22", "alerta" ) );
end

rule "40304361_490" 
	salience 490
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70015368") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90174569") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90279107") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 70015368, 90174569, 90279107 } realizados a partir do procedimento {40304361}. Prob: 89,47", "alerta" ) );
end

rule "40304361_489" 
	salience 489
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70705330") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90174569") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90279107") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 70705330, 90174569, 90279107 } realizados a partir do procedimento {40304361}. Prob: 89,47", "alerta" ) );
end

rule "40304361_488" 
	salience 488
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70705330") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90007131") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90019881") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 70705330, 90007131, 90019881 } realizados a partir do procedimento {40304361}. Prob: 89,47", "alerta" ) );
end

rule "40304361_487" 
	salience 487
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90174569") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90279107") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 70705348, 90174569, 90279107 } realizados a partir do procedimento {40304361}. Prob: 89,47", "alerta" ) );
end

rule "40304361_486" 
	salience 486
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70222789") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90007131") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90279107") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 70222789, 90007131, 90279107 } realizados a partir do procedimento {40304361}. Prob: 83,33", "alerta" ) );
end

rule "40304361_485" 
	salience 485
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70705330") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90007131") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90279107") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 70705330, 90007131, 90279107 } realizados a partir do procedimento {40304361}. Prob: 83,33", "alerta" ) );
end

rule "40304361_482" 
	salience 482
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60034335") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70015368") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70222789") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 60034335, 70015368, 70222789 } realizados a partir do procedimento {40304361}. Prob: 84,62", "alerta" ) );
end

rule "40304361_481" 
	salience 481
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60034335") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70015368") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705330") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 60034335, 70015368, 70705330 } realizados a partir do procedimento {40304361}. Prob: 84,62", "alerta" ) );
end

rule "40304361_480" 
	salience 480
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "162851") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705259") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90279107") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 162851, 70705259, 90279107 } realizados a partir do procedimento {40304361}. Prob: 93,33", "alerta" ) );
end

rule "40304361_479" 
	salience 479
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "124865") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705259") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 124865, 70705259 } realizados a partir do procedimento {40304361}. Prob: 90,00", "alerta" ) );
end

rule "40304361_478" 
	salience 478
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "124865") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70015368") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 124865, 70015368 } realizados a partir do procedimento {40304361}. Prob: 84,38", "alerta" ) );
end

rule "40304361_477" 
	salience 477
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "124865") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "162851") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 124865, 162851 } realizados a partir do procedimento {40304361}. Prob: 80,24", "alerta" ) );
end

rule "40304361_476" 
	salience 476
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "15800") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705259") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 15800, 70705259 } realizados a partir do procedimento {40304361}. Prob: 83,03", "alerta" ) );
end

rule "40304361_475" 
	salience 475
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60023252") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705259") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 60023252, 70705259 } realizados a partir do procedimento {40304361}. Prob: 81,63", "alerta" ) );
end

rule "40304361_474" 
	salience 474
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70705330") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90174569") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 70705330, 90174569 } realizados a partir do procedimento {40304361}. Prob: 81,82", "alerta" ) );
end

rule "40304361_473" 
	salience 473
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70015368") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90174569") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 70015368, 90174569 } realizados a partir do procedimento {40304361}. Prob: 81,82", "alerta" ) );
end

rule "40304361_472" 
	salience 472
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70705330") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90007131") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 70705330, 90007131 } realizados a partir do procedimento {40304361}. Prob: 80,77", "alerta" ) );
end

rule "40304361_471" 
	salience 471
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70222789") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90007131") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 70222789, 90007131 } realizados a partir do procedimento {40304361}. Prob: 80,77", "alerta" ) );
end

rule "40304361_469" 
	salience 469
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "251137") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705356") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 251137, 70705356 } realizados a partir do procedimento {40304361}. Prob: 81,48", "alerta" ) );
end

rule "40304361_466" 
	salience 466
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60034335") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70015368") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 60034335, 70015368 } realizados a partir do procedimento {40304361}. Prob: 85,00", "alerta" ) );
end

rule "40304361_465" 
	salience 465
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 2 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304361") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "124865") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304361","Itens { 124865 } realizados a partir do procedimento {40304361}. Prob: 80,56", "alerta" ) );
end

