package com.ops.expertsystem.regras.prestador.prestador_03;

rule "40101010_500" 
	salience 500
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40101010") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "64730") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "172145") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "60034335") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70204233") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40101010","Itens { 64730, 172145, 60034335, 70014370, 70139148, 70204233, 70705348, 70852375 } realizados a partir do procedimento {40101010}. Prob: 100,00", "alerta" ) );
end

rule "40101010_499" 
	salience 499
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40101010") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60001038") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70194084") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70204233") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40101010","Itens { 60001038, 70014370, 70139148, 70194084, 70204233, 70705348, 70852375 } realizados a partir do procedimento {40101010}. Prob: 100,00", "alerta" ) );
end

rule "40101010_498" 
	salience 498
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40101010") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60001038") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852278") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40101010","Itens { 60001038, 70014370, 70139148, 70705348, 70852278, 70852375, 90227255 } realizados a partir do procedimento {40101010}. Prob: 100,00", "alerta" ) );
end

rule "40101010_497" 
	salience 497
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40101010") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "64730") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "172145") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "60034335") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40101010","Itens { 64730, 172145, 60034335, 70014370, 70139148, 70705348 } realizados a partir do procedimento {40101010}. Prob: 100,00", "alerta" ) );
end

rule "40101010_496" 
	salience 496
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40101010") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90196325") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90269489") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40101010","Itens { 70014370, 90196325, 90269489 } realizados a partir do procedimento {40101010}. Prob: 100,00", "alerta" ) );
end

rule "40101010_495" 
	salience 495
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40101010") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90196325") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90269489") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40101010","Itens { 70139148, 90196325, 90269489 } realizados a partir do procedimento {40101010}. Prob: 100,00", "alerta" ) );
end

rule "40101010_494" 
	salience 494
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40101010") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90196325") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90269489") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40101010","Itens { 70705348, 90196325, 90269489 } realizados a partir do procedimento {40101010}. Prob: 100,00", "alerta" ) );
end

rule "40101010_493" 
	salience 493
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40101010") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "172145") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90123093") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90123107") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40101010","Itens { 172145, 90123093, 90123107 } realizados a partir do procedimento {40101010}. Prob: 100,00", "alerta" ) );
end

rule "40101010_492" 
	salience 492
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40101010") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "172145") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90196031") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40101010","Itens { 172145, 90196031 } realizados a partir do procedimento {40101010}. Prob: 83,33", "alerta" ) );
end

