package com.ops.expertsystem.regras.prestador.prestador_03;

rule "10102019_500" 
	salience 500
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "49081") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "60000805") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852278") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 49081, 60000805, 70014370, 70139148, 70705348, 70852278, 70852375, 90227255 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_499" 
	salience 499
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "72845") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "60000805") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852278") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 72845, 60000805, 70014370, 70139148, 70705348, 70852278, 70852375, 90227255 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_498" 
	salience 498
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "3953079") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "60000805") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90253132") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 3953079, 60000805, 70014370, 70139148, 70705348, 70852375, 90227255, 90253132 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_497" 
	salience 497
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "72845") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "3953079") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 72845, 3953079, 70014370, 70139148, 70705348, 70852375, 90227255 } realizados a partir do procedimento {10102019}. Prob: 83,33", "alerta" ) );
end

rule "10102019_496" 
	salience 496
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "49081") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "3953079") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 49081, 3953079, 70014370, 70139148, 70705348, 70852375, 90227255 } realizados a partir do procedimento {10102019}. Prob: 83,33", "alerta" ) );
end

rule "10102019_495" 
	salience 495
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "72845") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "60000805") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 72845, 60000805, 70014370, 70139148, 70705348, 70852375, 90227255 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_494" 
	salience 494
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "49081") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "60000805") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 49081, 60000805, 70014370, 70139148, 70705348, 70852375, 90227255 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_493" 
	salience 493
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60001038") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852278") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 60001038, 70014370, 70139148, 70705348, 70852278, 70852375, 90227255 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_492" 
	salience 492
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "49081") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70699224") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90196031") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 49081, 70699224, 70705348, 70852375, 90196031, 90227255 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_491" 
	salience 491
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "72845") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70699224") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90196031") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 72845, 70699224, 70705348, 70852375, 90196031, 90227255 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_490" 
	salience 490
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "72845") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852278") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90196031") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 72845, 70852278, 70852375, 90196031, 90227255 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_489" 
	salience 489
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "72845") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70699224") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852278") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 72845, 70699224, 70705348, 70852278, 90227255 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_488" 
	salience 488
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "72845") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70699224") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90253132") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 72845, 70699224, 70705348, 90227255, 90253132 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_487" 
	salience 487
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "49081") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70699224") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90253132") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 49081, 70699224, 70705348, 90227255, 90253132 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_486" 
	salience 486
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "49081") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852278") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90196031") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 49081, 70852278, 70852375, 90196031, 90227255 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_485" 
	salience 485
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "49081") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70699224") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852278") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 49081, 70699224, 70705348, 70852278, 90227255 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_484" 
	salience 484
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90185048") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90196031") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90253132") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 70852375, 90185048, 90196031, 90227255, 90253132 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_483" 
	salience 483
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "72845") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70194084") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 72845, 70194084, 70705348, 70852375 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_482" 
	salience 482
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "49081") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70194084") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 49081, 70194084, 70705348, 70852375 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_481" 
	salience 481
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "72845") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852278") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90253132") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 72845, 70852278, 90227255, 90253132 } realizados a partir do procedimento {10102019}. Prob: 85,71", "alerta" ) );
end

rule "10102019_480" 
	salience 480
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70852278") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90185048") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90253132") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 70852278, 90185048, 90227255, 90253132 } realizados a partir do procedimento {10102019}. Prob: 87,50", "alerta" ) );
end

rule "10102019_479" 
	salience 479
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "49081") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70699224") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 49081, 70699224, 70705348, 90227255 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_478" 
	salience 478
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "72845") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70699224") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 72845, 70699224, 70705348, 90227255 } realizados a partir do procedimento {10102019}. Prob: 100,00", "alerta" ) );
end

rule "10102019_477" 
	salience 477
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90185048") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90253132") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 70852375, 90185048, 90227255, 90253132 } realizados a partir do procedimento {10102019}. Prob: 87,50", "alerta" ) );
end

rule "10102019_476" 
	salience 476
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90070194") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 70705348, 90070194, 90227255 } realizados a partir do procedimento {10102019}. Prob: 83,33", "alerta" ) );
end

rule "10102019_475" 
	salience 475
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90070194") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 70014370, 90070194, 90227255 } realizados a partir do procedimento {10102019}. Prob: 83,33", "alerta" ) );
end

rule "10102019_474" 
	salience 474
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70852278") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90070194") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 70852278, 90070194, 90227255 } realizados a partir do procedimento {10102019}. Prob: 83,33", "alerta" ) );
end

rule "10102019_473" 
	salience 473
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "49081") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90070194") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 49081, 90070194, 90227255 } realizados a partir do procedimento {10102019}. Prob: 83,33", "alerta" ) );
end

rule "10102019_472" 
	salience 472
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90070194") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 70852375, 90070194, 90227255 } realizados a partir do procedimento {10102019}. Prob: 83,33", "alerta" ) );
end

rule "10102019_471" 
	salience 471
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "72845") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90070194") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 72845, 90070194, 90227255 } realizados a partir do procedimento {10102019}. Prob: 83,33", "alerta" ) );
end

rule "10102019_470" 
	salience 470
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90070194") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 70139148, 90070194, 90227255 } realizados a partir do procedimento {10102019}. Prob: 83,33", "alerta" ) );
end

rule "10102019_469" 
	salience 469
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "49081") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852278") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 49081, 70852278, 90227255 } realizados a partir do procedimento {10102019}. Prob: 87,50", "alerta" ) );
end

rule "10102019_468" 
	salience 468
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "72845") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852278") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 72845, 70852278, 90227255 } realizados a partir do procedimento {10102019}. Prob: 87,50", "alerta" ) );
end

rule "10102019_467" 
	salience 467
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "90185048") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90253132") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 90185048, 90227255, 90253132 } realizados a partir do procedimento {10102019}. Prob: 88,89", "alerta" ) );
end

rule "10102019_466" 
	salience 466
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "49081") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 49081, 90227255 } realizados a partir do procedimento {10102019}. Prob: 83,75", "alerta" ) );
end

rule "10102019_465" 
	salience 465
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "10102019") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "72845") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("10102019","Itens { 72845, 90227255 } realizados a partir do procedimento {10102019}. Prob: 83,75", "alerta" ) );
end

