package com.ops.expertsystem.regras.prestador.prestador_03;

rule "40805018_500" 
	salience 500
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40805018") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "3953079") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "60000805") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90253132") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40805018","Itens { 3953079, 60000805, 70014370, 70139148, 70705348, 70852375, 90227255, 90253132 } realizados a partir do procedimento {40805018}. Prob: 100,00", "alerta" ) );
end

rule "40805018_499" 
	salience 499
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40805018") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60001038") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70194084") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70204233") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40805018","Itens { 60001038, 70014370, 70139148, 70194084, 70204233, 70705348, 70852375 } realizados a partir do procedimento {40805018}. Prob: 100,00", "alerta" ) );
end

rule "40805018_498" 
	salience 498
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40805018") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60001038") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852278") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40805018","Itens { 60001038, 70014370, 70139148, 70705348, 70852278, 70852375, 90227255 } realizados a partir do procedimento {40805018}. Prob: 100,00", "alerta" ) );
end

rule "40805018_497" 
	salience 497
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40805018") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60022965") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40805018","Itens { 60022965, 70014370, 70705348 } realizados a partir do procedimento {40805018}. Prob: 80,00", "alerta" ) );
end

rule "40805018_496" 
	salience 496
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40805018") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60022965") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90123093") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90196031") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40805018","Itens { 60022965, 90123093, 90196031 } realizados a partir do procedimento {40805018}. Prob: 83,33", "alerta" ) );
end

rule "40805018_495" 
	salience 495
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40805018") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60022965") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90123093") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40805018","Itens { 60022965, 90123093 } realizados a partir do procedimento {40805018}. Prob: 85,71", "alerta" ) );
end

rule "40805018_494" 
	salience 494
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40805018") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60022965") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90123107") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40805018","Itens { 60022965, 90123107 } realizados a partir do procedimento {40805018}. Prob: 80,00", "alerta" ) );
end

rule "40805018_493" 
	salience 493
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40805018") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60022965") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90148673") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40805018","Itens { 60022965, 90148673 } realizados a partir do procedimento {40805018}. Prob: 80,00", "alerta" ) );
end

