package com.ops.expertsystem.regras.prestador.prestador_03;

rule "40311210_500" 
	salience 500
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40311210") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "49081") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "72845") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852278") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40311210","Itens { 49081, 72845, 70014370, 70139148, 70705348, 70852278, 70852375 } realizados a partir do procedimento {40311210}. Prob: 83,33", "alerta" ) );
end

rule "40311210_499" 
	salience 499
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40311210") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "49081") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "72845") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40311210","Itens { 49081, 72845, 70014370, 70139148, 70705348, 70852375 } realizados a partir do procedimento {40311210}. Prob: 85,71", "alerta" ) );
end

rule "40311210_498" 
	salience 498
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40311210") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60033720") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70176086") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70848645") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40311210","Itens { 60033720, 70176086, 70705348, 70848645 } realizados a partir do procedimento {40311210}. Prob: 83,33", "alerta" ) );
end

rule "40311210_497" 
	salience 497
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40311210") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60033746") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70176086") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70848645") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40311210","Itens { 60033746, 70176086, 70705348, 70848645 } realizados a partir do procedimento {40311210}. Prob: 83,33", "alerta" ) );
end

rule "40311210_496" 
	salience 496
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40311210") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70194084") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90185048") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90253132") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40311210","Itens { 70194084, 90185048, 90253132 } realizados a partir do procedimento {40311210}. Prob: 100,00", "alerta" ) );
end

rule "40311210_495" 
	salience 495
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40311210") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90185048") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90253132") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40311210","Itens { 70852375, 90185048, 90253132 } realizados a partir do procedimento {40311210}. Prob: 100,00", "alerta" ) );
end

rule "40311210_494" 
	salience 494
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40311210") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90185048") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40311210","Itens { 70705348, 90185048 } realizados a partir do procedimento {40311210}. Prob: 100,00", "alerta" ) );
end

rule "40311210_493" 
	salience 493
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40311210") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90185048") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40311210","Itens { 70014370, 90185048 } realizados a partir do procedimento {40311210}. Prob: 100,00", "alerta" ) );
end

rule "40311210_492" 
	salience 492
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40311210") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90185048") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40311210","Itens { 70139148, 90185048 } realizados a partir do procedimento {40311210}. Prob: 100,00", "alerta" ) );
end

rule "40311210_491" 
	salience 491
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40311210") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90217853") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40311210","Itens { 70705348, 90217853 } realizados a partir do procedimento {40311210}. Prob: 83,33", "alerta" ) );
end

rule "40311210_490" 
	salience 490
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40311210") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90217853") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40311210","Itens { 70139148, 90217853 } realizados a partir do procedimento {40311210}. Prob: 83,33", "alerta" ) );
end

rule "40311210_489" 
	salience 489
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40311210") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90217853") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40311210","Itens { 70014370, 90217853 } realizados a partir do procedimento {40311210}. Prob: 83,33", "alerta" ) );
end

