package com.ops.expertsystem.regras.prestador.prestador_03;

rule "40304922_500" 
	salience 500
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304922") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60001038") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70194084") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70204233") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304922","Itens { 60001038, 70014370, 70139148, 70194084, 70204233, 70705348, 70852375 } realizados a partir do procedimento {40304922}. Prob: 100,00", "alerta" ) );
end

rule "40304922_499" 
	salience 499
	when
		$metaRegra: com.ops.expertsystem.auxiliar.AtivaRegraAssociacao(codigoPrestador == 3 )
		com.ops.expertsystem.Guia(movs: movimentos)
		com.ops.expertsystem.Movimento(codigoMovimento == "40304922") from movs

		com.ops.expertsystem.Movimento(codigoMovimento == "60001038") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70014370") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70139148") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70705348") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852278") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "70852375") from movs
		com.ops.expertsystem.Movimento(codigoMovimento == "90227255") from movs
	then
		retract( $metaRegra );
		insert( new com.ops.expertsystem.analise.Item("40304922","Itens { 60001038, 70014370, 70139148, 70705348, 70852278, 70852375, 90227255 } realizados a partir do procedimento {40304922}. Prob: 100,00", "alerta" ) );
end

