package com.ops.expertsystem.analise;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Item implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String codigoProcedimento;
	private java.lang.String descricao;
	private java.lang.String categoria;

	public Item() {
	}

	public java.lang.String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(java.lang.String descricao) {
		this.descricao = descricao;
	}

	public java.lang.String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(java.lang.String categoria) {
		this.categoria = categoria;
	}

	public java.lang.String getCodigoProcedimento() {
		return this.codigoProcedimento;
	}

	public void setCodigoProcedimento(java.lang.String codigoProcedimento) {
		this.codigoProcedimento = codigoProcedimento;
	}

	public Item(java.lang.String codigoProcedimento,
			java.lang.String descricao, java.lang.String categoria) {
		this.codigoProcedimento = codigoProcedimento;
		this.descricao = descricao;
		this.categoria = categoria;
	}

}
