package com.ops.expertsystem.analise;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Resultado implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.ops.expertsystem.analise.Item> itens;

	public Resultado() {
	}

	public java.util.List<com.ops.expertsystem.analise.Item> getItens() {
		return this.itens;
	}

	public void setItens(java.util.List<com.ops.expertsystem.analise.Item> itens) {
		this.itens = itens;
	}

	public Resultado(java.util.List<com.ops.expertsystem.analise.Item> itens) {
		this.itens = itens;
	}

}
