package com.ops.expertsystem.auxiliar;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AtivaRegraAssociacao implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int codigoPrestador;

	public AtivaRegraAssociacao() {
	}

	public int getCodigoPrestador() {
		return this.codigoPrestador;
	}

	public void setCodigoPrestador(int codigoPrestador) {
		this.codigoPrestador = codigoPrestador;
	}

	public AtivaRegraAssociacao(int codigoPrestador) {
		this.codigoPrestador = codigoPrestador;
	}

}
