package com.ops.expertsystem.containercontrato;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Contrato implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer idContrato;
	private java.util.Date inicio;
	private java.util.Date fim;

	private java.util.List<com.ops.expertsystem.containercontrato.Procedimento> procedimentos;

	public Contrato() {
	}

	public java.lang.Integer getIdContrato() {
		return this.idContrato;
	}

	public void setIdContrato(java.lang.Integer idContrato) {
		this.idContrato = idContrato;
	}

	public java.util.Date getInicio() {
		return this.inicio;
	}

	public void setInicio(java.util.Date inicio) {
		this.inicio = inicio;
	}

	public java.util.Date getFim() {
		return this.fim;
	}

	public void setFim(java.util.Date fim) {
		this.fim = fim;
	}

	public java.util.List<com.ops.expertsystem.containercontrato.Procedimento> getProcedimentos() {
		return this.procedimentos;
	}

	public void setProcedimentos(
			java.util.List<com.ops.expertsystem.containercontrato.Procedimento> procedimentos) {
		this.procedimentos = procedimentos;
	}

	public Contrato(
			java.lang.Integer idContrato,
			java.util.Date inicio,
			java.util.Date fim,
			java.util.List<com.ops.expertsystem.containercontrato.Procedimento> procedimentos) {
		this.idContrato = idContrato;
		this.inicio = inicio;
		this.fim = fim;
		this.procedimentos = procedimentos;
	}

}
