package com.ops.expertsystem.containercontrato;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Prestador implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer codigoPrestador;
	private java.util.List<com.ops.expertsystem.containercontrato.Contrato> contratos;

	public Prestador() {
	}

	public java.lang.Integer getCodigoPrestador() {
		return this.codigoPrestador;
	}

	public void setCodigoPrestador(java.lang.Integer codigoPrestador) {
		this.codigoPrestador = codigoPrestador;
	}

	public java.util.List<com.ops.expertsystem.containercontrato.Contrato> getContratos() {
		return this.contratos;
	}

	public void setContratos(
			java.util.List<com.ops.expertsystem.containercontrato.Contrato> contratos) {
		this.contratos = contratos;
	}

	public Prestador(
			java.lang.Integer codigoPrestador,
			java.util.List<com.ops.expertsystem.containercontrato.Contrato> contratos) {
		this.codigoPrestador = codigoPrestador;
		this.contratos = contratos;
	}

}
