package com.ops.expertsystem.containercontrato;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Procedimento implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String codigoProcedimento;
	private java.lang.Double valor;

	public Procedimento() {
	}

	public java.lang.Double getValor() {
		return this.valor;
	}

	public void setValor(java.lang.Double valor) {
		this.valor = valor;
	}

	public java.lang.String getCodigoProcedimento() {
		return this.codigoProcedimento;
	}

	public void setCodigoProcedimento(java.lang.String codigoProcedimento) {
		this.codigoProcedimento = codigoProcedimento;
	}

	public Procedimento(java.lang.String codigoProcedimento,
			java.lang.Double valor) {
		this.codigoProcedimento = codigoProcedimento;
		this.valor = valor;
	}

}
