package com.ops.expertsystem;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Guia implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;
	private int codigoPrestador;

	private java.util.List<com.ops.expertsystem.Movimento> movimentos;

	public Guia() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public int getCodigoPrestador() {
		return this.codigoPrestador;
	}

	public void setCodigoPrestador(int codigoPrestador) {
		this.codigoPrestador = codigoPrestador;
	}

	public java.util.List<com.ops.expertsystem.Movimento> getMovimentos() {
		return this.movimentos;
	}

	public void setMovimentos(
			java.util.List<com.ops.expertsystem.Movimento> movimentos) {
		this.movimentos = movimentos;
	}

	public Guia(java.lang.String id, int codigoPrestador,
			java.util.List<com.ops.expertsystem.Movimento> movimentos) {
		this.id = id;
		this.codigoPrestador = codigoPrestador;
		this.movimentos = movimentos;
	}

}
