package com.ops.expertsystem;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Movimento implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer codigoTabela;
	private java.lang.String codigoMovimento;
	private java.lang.String descricao;
	private java.lang.Double valorTotal;
	private java.lang.Double quantidadeExecutada;
	private java.util.Date dataExecucao;

	public Movimento() {
	}

	public java.lang.Integer getCodigoTabela() {
		return this.codigoTabela;
	}

	public void setCodigoTabela(java.lang.Integer codigoTabela) {
		this.codigoTabela = codigoTabela;
	}

	public java.lang.String getCodigoMovimento() {
		return this.codigoMovimento;
	}

	public void setCodigoMovimento(java.lang.String codigoMovimento) {
		this.codigoMovimento = codigoMovimento;
	}

	public java.lang.String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(java.lang.String descricao) {
		this.descricao = descricao;
	}

	public java.lang.Double getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(java.lang.Double valorTotal) {
		this.valorTotal = valorTotal;
	}

	public java.lang.Double getQuantidadeExecutada() {
		return this.quantidadeExecutada;
	}

	public void setQuantidadeExecutada(java.lang.Double quantidadeExecutada) {
		this.quantidadeExecutada = quantidadeExecutada;
	}

	public java.util.Date getDataExecucao() {
		return this.dataExecucao;
	}

	public void setDataExecucao(java.util.Date dataExecucao) {
		this.dataExecucao = dataExecucao;
	}

	public Movimento(java.lang.Integer codigoTabela,
			java.lang.String codigoMovimento, java.lang.String descricao,
			java.lang.Double valorTotal, java.lang.Double quantidadeExecutada,
			java.util.Date dataExecucao) {
		this.codigoTabela = codigoTabela;
		this.codigoMovimento = codigoMovimento;
		this.descricao = descricao;
		this.valorTotal = valorTotal;
		this.quantidadeExecutada = quantidadeExecutada;
		this.dataExecucao = dataExecucao;
	}

}
